# Generated by Django 3.1.4 on 2024-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gerente_ventas',
            field=models.BooleanField(default=False),
        ),
    ]
