# Generated by Django 3.1.4 on 2024-05-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240509_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
